### ISSUE TITLE
history of particular resource returns history of all resources of that type

### ISSUE THREAD

**Issue by joannanowakowska** [fhirbase/fhirbase#100]
The following query returns all Patient resources available in the Fhirbase db:
SELECT fhir.history('Patient', 'aa878b5e-a1e9-4dc6-9e5c-d61e44699e33');

**Comment by niquola** [comment]
History api has been changed (see #78).

Use:

```sql
select fhir.history('Patient', '_count=10&since=2012');
select fhir.history('Patient', id, '_count=10&since=2012');
```

**Comment by joannanowakowska** [comment]
Thank you for quick response. 

Just to confirm, all the versions of a particular resource can be obtained passing empty parameter string, right?

```sql
select fhir.history('Patient', id, '');
```
It also looks that parameters can either be provided beginning with or without an underscore

**Comment by niquola** [comment]
Yes, if amount of versions not greater then 100 (https://github.com/fhirbase/fhirbase/blob/master/src/fhirbase_history.sql#L39), this is a guard against overload. But you can always expand this limit with:
```sql
select fhir.history('Patient', id, '_count=1000');
```

or use paging with `_page` parameter.
