### ISSUE TITLE
Deletion does not create a new version of the resource that would be marked as deleted

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase#103]
Deletion in current implementation creates moves an existing resource instance to the history and does not create a version that would mark the resource as deleted. The standard s

That later causes that when user retrieves resource instance history it is impossible to recognise if the last version has been deleted or not.

**Comment by niquola** [comment]
@Andrzej-Pietrzak have you seen in FHIR sepc how to specify deletion marker/label?

Now in fhirbase we use convention - if logical_id is present in history and not present in resource table - than it's deleted. It is quite simple to add deletion label/marker to last history record (in fhir.delete proc), but i do not know how to show this in history bundle (with meta?).

Could you send question to FHIR leaders in fhir mailing list or in a skype chat?

**Comment by Andrzej-Pietrzak** [comment]
According to this spec: http://hl7.org/implement/standards/fhir/2015May/http.html#history 
the history bundle should contain entries appended with a transaction. That node would have the method name specified - for delete we could expect something like:
<transaction>
    <method value="DELETE"/>
    <url value="{ResourceName}/{id}"/>
</transaction>
as json:
{
    "transaction": {
        "method": "DELETE",
        "url": "{ResourceName}/{id}"
    }
}
 

Correct me if I'm wrong but basically couldn't we just start storing the transaction information in another column and change the history retrieval method to include it ? The deletion would be consistent with creation - moving old resource and creating a new empty one with only transaction information.

**Comment by niquola** [comment]
Moved to https://github.com/fhirbase/fhirbase-plv8/issues/17
