### ISSUE TITLE
Search by date using "not equals" comparator returns empty results

### ISSUE THREAD

**Issue by grzegorz-borczuch** [fhirbase/fhirbase#104]
It's a duplicate of https://github.com/fhirbase/fhirbase/issues/93

After the commit done by @niquola, I've tested this again and this is the result:

Using =!= comparator in FhirBase always returns empty results.
Looks like this comparator is not recognised, because in SQL that get's generated it's comparing dates to NULL. See SQL code generated below:

```
SELECT patient.version_id, patient.logical_id, patient.resource_type, patient.updated, patient.published, patient.category, patient.content FROM patient

WHERE (not  (fhirbase_date_idx.index_as_date(content, '{birthDate}'::text[], 'date'::text) && NULL))
LIMIT 100
OFFSET 0
```

**Comment by niquola** [comment]
Moved to https://github.com/fhirbase/fhirbase-plv8/issues/27
