### ISSUE TITLE
Installing fhirbase with most recent fhirbase.sql from fhirbase build running query in Pgadmin

### ISSUE THREAD

**Issue by acrighton** [fhirbase/fhirbase#105]
ERROR:  syntax error at or near "{"
LINE 4381: {ConceptMap,concept,map,product,concept} uri
           ^
********** Error **********

ERROR: syntax error at or near "{"
SQL state: 42601
Character: 158595

**Comment by niquola** [comment]
fhirbase could be installed only with psql util as ordinary pg dump. Do you have psql?

**Comment by acrighton** [comment]
Yes I have psql will use that thanks
