### ISSUE TITLE
FhirBase search returns if key matches the searched value

### ISSUE THREAD

**Issue by KrzysztofKowalskiKainos** [fhirbase/fhirbase#108]
It seems that FhirBase search is based on searching substring in contents of search target serialized as string "WHERE (fhirbase_idx_fns.index_as_string([resource].content, '{[searched_phrase]}') ilike '%e%')" For example if we have patient with name: { "text": "Ivan" } and we search with query: name=e the mentioned patient will be returned because 'text' contains searched value.

**Comment by niquola** [comment]
Do you think this behavior is wrong?

**Comment by niquola** [comment]
O, you mean we are searching in json keys!
Yes this is a bug.

**Comment by niquola** [comment]
Fixed in plv8 version
