### ISSUE TITLE
Error trying to run fhirbase container

### ISSUE THREAD

**Issue by davecrumbacher** [fhirbase/fhirbase#111]
When running the fhirbase container on a Mac using Virtualbox, as well as on an Ubuntu instance, I get this error:

```
2015-05-20 01:06:28 UTC [1-1] FATAL:  private key file "/etc/ssl/private/ssl-cert-snakeoil.key" has group or world access
2015-05-20 01:06:28 UTC [1-2] DETAIL:  File must be owned by the database user or root, must have no write permission for "group", and must have no permissions for "other".
```

Any ideas?

**Comment by niquola** [comment]
Hi Dave,

There is some bugs in docker (https://github.com/Painted-Fox/docker-postgresql/issues/30)

I've fixed Dockerfile, but could not upload it on dockerhub (some bugs/fails storm is there :(

Please wait or build docker with fhirbase locally - https://github.com/fhirbase/fhirbase/blob/master/dockerhelp

**Comment by davecrumbacher** [comment]
Thanks for the quick response, Niquola.  Can we leave this issue open and then you can close it when you are able to upload the fix to dockerhub?

**Comment by niquola** [comment]
I've switched to VirtualBox vagrant and it should work:

Please checkout latest version and 
```sh
git clone https://github.com/fhirbase/fhirbase.git
cd fhirbase
vagrant destroy
vagrant up --provider=virtualbox # this could take a while
```
Test using ssh & shell
```sh
vagrant ssh
docker run  --rm --volumes-from=fhirbase -i -t quay.io/fhirbase/fhirbase:0.0.12 psql fhirbase
```
or you could connect directly using forwarded ports (https://github.com/fhirbase/fhirbase/blob/master/Vagrantfile#L9) 

```yml
host: localhost
port: 2345
user: fhirbase
password: fhirbase
database: fhirbase
```
