### ISSUE TITLE
Wrong status returned when vreading a deleted resource version

### ISSUE THREAD

**Issue by szymonh** [fhirbase/fhirbase#112]
In the current implementation of FHIRBase vreading the deleted instance version returns the instance while FHIR specification suggests using gone response status (410).

"
The Version Id (vid) is an opaque identifier that conforms to the same format requirements as a Logical Id. The id may have been found by performing a history interaction (see below), by recording the version id from a content location returned from a read or from a version specific reference in a content model. If the version referred to is actually one where the resource was deleted, the server should return a 410 status code.
"

**Comment by niquola** [comment]
Thx, no i'm working on huge refactoring fhirbase to plv8 - so it could take some time to fix this bugs

**Comment by niquola** [comment]
moved to https://github.com/fhirbase/fhirbase-plv8/issues/17
