### ISSUE TITLE
Correct version required in meta.versionId for successful update operation

### ISSUE THREAD

**Issue by szymonh** [fhirbase/fhirbase#114]
According to the FHIR standard meta.versionId and meta.lastUpdated should be ignored during instance update. The current behaviour of FHIR base is such that the update operation not only fails to ignore the existing meta.versionId but does not allow updates with no meta.versionId present in the request. When attempting to update some resource instance with no meta.versionId the following error is returned:

"{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":{"coding":[{"system":"http://hl7.org/fhir/issue-type","code":"invalid","display":"Invalid Content"},{"system":"http://hl7.org/fhir/http-code","code":"422","display":"Unprocessable Entity"}]},"details":"If you pass meta.versionId we go against FHIR spec and check for version conflicts. Expected last versionId fdd708e6-c3b4-4787-b243-db6da71ed69b, but got "}]}"

Quote from FHIR standard:
"The request body SHALL be a Resource with an id element that has an identical value to the [id] in the URL. If the request body includes a meta, the server SHALL ignore the existing versionId and lastUpdated values. The server SHALL populate the meta.versionId and meta.lastUpdated with the new correct values. Servers are allowed to review and alter the other metadata values, but SHOULD refrain from doing so (see metadata description for further information)."

**Comment by niquola** [comment]
Will be addressed in - https://github.com/fhirbase/fhirbase-plv8/issues/17
