### ISSUE TITLE
Search Patient by telecom doesn't work

### ISSUE THREAD

**Issue by mschielmann** [fhirbase/fhirbase#117]
Search Patient Resource by telecom doesn't work. From FHIR spec:
"The value in any kind of telecom details of the patient"
For patient with telecom:
```
  "telecom": [
    {
      "use": "home",
      "value": "111222333",
      "system": "phone"
    },
    {
      "use": "work",
      "value": "444555666",
      "system": "phone"
    }
  ]
```
search by `telecom=111222333` doesn't work.
The created sql is:
```
fhirbase_idx_fns.index_contactpoint_as_token(patient.content, '{telecom}') && '{111222333}'::text[]
```
Where the index_contactpoint_as_token returns:
```
{phone|111222333,phone|444555666}
```
and it doesn't match {111222333}.
If the index_contactpoint_as_token returned only values:
```
{111222333,444555666}
```
it would work fine.

**Comment by niquola** [comment]
Moved to https://github.com/fhirbase/fhirbase-plv8/issues/23
