### ISSUE TITLE
Search Patient by deceased/deathtime doesn't work.

### ISSUE THREAD

**Issue by mschielmann** [fhirbase/fhirbase#118]
Search Patient by deceased/deathtime doesn't work.
When searching by deathtime generated sql looks like this:
```
fhirbase_date_idx.index_as_date(content, '{"*[starts-with(local-name(.), ''deceased'')]"}'::text[], NULL::text)
```
which is not working. When changed to:
```
fhirbase_date_idx.index_as_date(content, '{deceasedDateTime}'::text[], 'date'::text)
```
it works fine.

Search for deceased token also doesn't work, as the generated sql is:
```
fhirbase_idx_fns.index_ups_as_token(patient.content, '{"*[starts-with(local-name(.), ''deceased'')]"}') && '{true}'::text[] --not working
```
which throws an exception that index_ups_as_token function is not found.
As the values of deceased can only be true/false it may be search the same as i.e. gender:
```
fhirbase_idx_fns.index_primitive_as_token(patient.content, '{deceasedBoolean}') && '{true}'::text[]
```
The above example works fine.

**Comment by niquola** [comment]
Thx, this is problem with metainformation. I think, we have to interpret xpath for such cases manualy :( I'm not ready to write xpath to json translator.

**Comment by mschielmann** [comment]
I don't get the xpath part, I'm sorry if I'm missing something obvious :/
Why is search for `deceased=true` different from `active=true` or `gender=male`?
Isn't search for `deathdate=2015-05-05` the same as search for `birthdate=2015-05-05`?

**Comment by niquola** [comment]
Will be addressed by https://github.com/fhirbase/fhirbase-plv8/issues/13
