### ISSUE TITLE
Installation doc inaccurate for development

### ISSUE THREAD

**Issue by lhitc** [fhirbase/fhirbase#122]
On Ubuntu (at least 14.04 plus PostgreSQL official package repository) the package "postgresql-9.4-plv8" is also required, else "./runme integrate" will fail.

**Comment by niquola** [comment]
Thx, I'll fix it

**Comment by niquola** [comment]
postgresql-9.4-plv8 become foundation of next version - https://github.com/fhirbase/fhirbase-plv8
