### ISSUE TITLE
Remove patient data

### ISSUE THREAD

**Issue by filip-owczarzak** [fhirbase/fhirbase#123]
In order to comply with [HIPAA Privacy Rule](http://privacyruleandresearch.nih.gov/pr_08.asp) which requires to de-identify protected health information, there is a need to implement a functionality which completely removes patient record, its history and all references in related resources. That is something different than delete operation in FHIR specification. Bear in mind de-identification itself may leave orphant resources, like Observation of certain measure not related to any specific patient.

**Comment by niquola** [comment]
In new version of fhirbase, we are going add `drop` operation, which remove resource and it's history.
So this functionality could be built on top of `drop`. We also could remove all resources with subject points to patient. After migration most of code to plv8, i hope you could join development :)
