### ISSUE TITLE
StructureDefinition resource lacks versioning

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase#125]
Structure definition does not contain version_ids.
This seems quite inconsistent with other resources, and does not allow me to keep track of any changes that were applied to that resource (and those changes are major events) in any other way than going through the web application logs.

What was the reason behind not assigning any version_id's to StructureDefinition resource ?
How do I use the fhirbase api to proceed with an update on that resource - should I remove the structure definition, insert a new one and generate the table again ?

**Comment by niquola** [comment]
It inherits version-id from resource table.
