### ISSUE TITLE
Reference search resource type discriminator support

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase#128]
According to fhir spec:

Some references are allowed to point to more than one type of resource. e.g. subject : Reference(Patient|Group|Device|..). In these cases, multiple different resources may have the same logical identifier. In this case, the client can specify a type modifier after the name of the parameter to be explicit about the intended type:

 GET [base]/Condition?subject:Patient=23

Resource type discriminator support is in plan for future releases ?

**Comment by niquola** [comment]
Why not, may be it works now - have you tried?
