### ISSUE TITLE
some tables lack primary key

### ISSUE THREAD

**Issue by wanghaisheng** [fhirbase/fhirbase#130]
what is the intention of missing primary key to some tables
```
	tests.results does not have a primary key.
	fhirbase_migration_201502270000_metadata_up.search_type_to_type does not have a primary key.
	fhirbase_migration_201502270000_metadata_up.hardcoded_complex_params does not have a primary key.
	public.resource_history does not have a primary key.
	public.resource does not have a primary key.
```

**Comment by niquola** [comment]
This tables are base for inheritance (no records in them):

public.resource_history does not have a primary key.
public.resource does not have a primary key.

Other are temporal or helper tables in migrations - that's ok
