### ISSUE TITLE
indexes are not created for references

### ISSUE THREAD

**Issue by sourix** [fhirbase/fhirbase#131]
We noticed that indexes were not created for the reference types in the latest version of fhirbase.

The following steps were performed.
Installed the latest version of fhirbase from master.
ran fhir.generate_tables() -- 187 tables exist in the "public" schema.
ran fhir.index_all_resources -- many indexes created, but no indexes to reference types.

To double check also ran fhir.index_search_param('Encounter', 'patient')
Could not find any new index created after the above command.

Because there are no indexes for reference types, running a query like the following takes an enormous amount of time with 1M patients and 1.3M Encounters

select fhir._search('Encounter', 'patient:Patient.name=Choy&_count=100&patient:Patient.organization:Organization.name=Lectus')

Am I doing something wrong or is this a defect with the index creation?

**Comment by niquola** [comment]
I'll check it tomorrow.
Could you  try to create this specific index with:
```sql
select fhir.index_search_param('Encounter','patient');
```

And dump execution plan with:

```sql
select fhir.explain_search('Encounter', 'patient:Patient.name=Choy&_count=100&patient:Patient.organization:Organization.name=Lectus')
```

**Comment by niquola** [comment]
Also (if you've batched this data) try to run vacuum analyze on this tables or whole database - http://www.postgresql.org/docs/9.4/static/sql-vacuum.html.
May be database statistic is not yet collected :)

**Comment by sourix** [comment]
We tried to create the specific index with
select fhir.index_search_param('Encounter','patient');

find below the execution plan for 

select fhir.explain_search('Encounter', 'patient:Patient.name=Choy&_count=100&patient:Patient.organization:Organization.name=Lectus')

                                                                           explain_search
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=98.25..2758.94 rows=100 width=459) (actual time=600.399..600.399 rows=0 loops=1)
   ->  Nested Loop  (cost=98.25..28380802.42 rows=1066666 width=459) (actual time=600.398..600.398 rows=0 loops=1)
         Join Filter: (fhirbase_idx_fns.index_as_reference(encounter.content, '{patient}'::text[]) && ARRAY[patient.logical_id])
         ->  Seq Scan on encounter  (cost=0.00..83509.33 rows=1333333 width=459) (actual time=0.003..289.253 rows=1333333 loops=1)
         ->  Materialize  (cost=98.25..30633.69 rows=80 width=37) (actual time=0.000..0.000 rows=0 loops=1333333)
               ->  Nested Loop  (cost=98.25..30633.29 rows=80 width=37) (actual time=64.259..64.259 rows=0 loops=1)
                     Join Filter: (fhirbase_idx_fns.index_as_reference(patient.content, '{managingOrganization}'::text[]) && ARRAY[organization.logical_id])
                     Rows Removed by Join Filter: 161
                     ->  Seq Scan on organization  (cost=0.00..157.89 rows=1 width=37) (actual time=0.511..32.190 rows=7 loops=1)
                           Filter: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Lectus%'::text)
                           Rows Removed by Filter: 484
                     ->  Bitmap Heap Scan on patient  (cost=98.25..28375.40 rows=8000 width=1173) (actual time=0.460..3.010 rows=23 loops=7)
                           Recheck Cond: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Choy%'::text)
                           Rows Removed by Index Recheck: 5
                           Heap Blocks: exact=189
                           ->  Bitmap Index Scan on fb_patient_name_name_string_idx  (cost=0.00..96.25 rows=8000 width=0) (actual time=0.321..0.321 rows=28 loops=7)
                                 Index Cond: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Choy%'::text)
 Planning time: 0.500 ms
 Execution time: 600.450 ms
(19 rows)

**Comment by chinnitv** [comment]
We were able to work around the problem of reference indexes not getting created by running the below queries.
`psql -U fhirbase -c "select fhirbase_indexing._index_reference_exp(searchparameter.*) from searchparameter where search_type='reference'" >fhirbase_ref_indexes.sql`
and then executing the CREATE INDEX statements.
Didn't yet look into why those are not getting created automatically either by fhir.index_all_resources() or by fhir.index_search_param('Encounter','patient')

However the trigram indexes on name(fb_<resource>_name_name_string_idx) are not getting used always. Here are 3 execution plans for search on Encounters for 3 different patient name filters Mc, Abe,Ch within the Mollis organization. The query times range from 480ms to 10 seconds.
One thing that I found was that queries with limit are not hitting the trigram index whereas queries without limit are hitting the trigram index.

`fhirbase=# select fhir.explain_search('Encounter', 'patient:Patient.name=Mc&_count=100&patient:Patient.organization:Organization.name=Mollis');`
                                                                                       explain_search
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=221.07..524.18 rows=100 width=459) (actual time=12.233..381.000 rows=100 loops=1)
   ->  Nested Loop  (cost=221.07..202291.18 rows=66667 width=459) (actual time=12.232..380.983 rows=100 loops=1)
         ->  Nested Loop  (cost=97.65..170521.03 rows=5 width=37) (actual time=12.179..378.172 rows=73 loops=1)
               ->  Seq Scan on organization  (cost=0.00..157.89 rows=5 width=37) (actual time=0.290..14.118 rows=3 loops=1)
                     Filter: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Mollis%'::text)
                     Rows Removed by Filter: 224
               ->  Bitmap Heap Scan on patient  (cost=97.65..34072.62 rows=1 width=1173) (actual time=10.481..121.335 rows=24 loops=3)
                     Recheck Cond: (fhirbase_idx_fns.index_as_reference(content, '{managingOrganization}'::text[]) && ARRAY[organization.logical_id])
                     Filter: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Mc%'::text)
                     Rows Removed by Filter: 1369
                     Heap Blocks: exact=4181
                     ->  Bitmap Index Scan on fb_patient_organization_managingorganization_reference_idx  (cost=0.00..97.65 rows=10000 width=0) (actual time=0.715..0.715 rows=2037 loops=3)
                           Index Cond: (fhirbase_idx_fns.index_as_reference(content, '{managingOrganization}'::text[]) && ARRAY[organization.logical_id])
         ->  Bitmap Heap Scan on encounter  (cost=123.42..6220.70 rows=13333 width=459) (actual time=0.034..0.035 rows=1 loops=73)
               Recheck Cond: (fhirbase_idx_fns.index_as_reference(content, '{patient}'::text[]) && ARRAY[patient.logical_id])
               Heap Blocks: exact=100
               ->  Bitmap Index Scan on fb_encounter_patient_patient_reference_idx  (cost=0.00..120.09 rows=13333 width=0) (actual time=0.031..0.031 rows=1 loops=73)
                     Index Cond: (fhirbase_idx_fns.index_as_reference(content, '{patient}'::text[]) && ARRAY[patient.logical_id])
 Planning time: 1.106 ms
 Execution time: 381.077 ms
(20 rows)

`fhirbase=# select fhir.explain_search('Encounter', 'patient:Patient.name=Ch&_count=100&patient:Patient.organization:Organization.name=Mollis');`
                                                                            explain_search
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=124.99..154.05 rows=100 width=459) (actual time=6.475..10117.160 rows=100 loops=1)
   ->  Nested Loop  (cost=124.99..15653743.78 rows=53872189 width=459) (actual time=6.475..10117.119 rows=100 loops=1)
         ->  Nested Loop  (cost=20.29..536272.99 rows=4040 width=37) (actual time=6.427..10111.780 rows=73 loops=1)
               Join Filter: (fhirbase_idx_fns.index_as_reference(patient.content, '{managingOrganization}'::text[]) && ARRAY[organization.logical_id])
               Rows Removed by Join Filter: 38986
               ->  Seq Scan on patient  (cost=0.00..429167.00 rows=80808 width=1173) (actual time=0.229..7787.655 rows=9765 loops=1)
                     Filter: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Ch%'::text)
                     Rows Removed by Filter: 78161
               ->  Materialize  (cost=20.29..35.40 rows=5 width=37) (actual time=0.000..0.001 rows=4 loops=9765)
                     ->  Bitmap Heap Scan on organization  (cost=20.29..35.37 rows=5 width=37) (actual time=0.198..0.452 rows=4 loops=1)
                           Recheck Cond: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Mollis%'::text)
                           Heap Blocks: exact=4
                           ->  Bitmap Index Scan on fb_organization_name_name_string_idx  (cost=0.00..20.29 rows=5 width=0) (actual time=0.031..0.031 rows=4 loops=1)
                                 Index Cond: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Mollis%'::text)
         ->  Bitmap Heap Scan on encounter  (cost=104.71..3608.62 rows=13333 width=459) (actual time=0.064..0.067 rows=1 loops=73)
               Recheck Cond: (fhirbase_idx_fns.index_as_reference(content, '{patient}'::text[]) && ARRAY[patient.logical_id])
               Heap Blocks: exact=100
               ->  Bitmap Index Scan on fb_encounter_patient_patient_reference_idx  (cost=0.00..101.37 rows=13333 width=0) (actual time=0.051..0.051 rows=1 loops=73)
                     Index Cond: (fhirbase_idx_fns.index_as_reference(content, '{patient}'::text[]) && ARRAY[patient.logical_id])
 Planning time: 0.761 ms
 Execution time: 10117.225 ms
(21 rows)

`fhirbase=# select fhir.explain_search('Encounter', 'patient:Patient.name=Abe&_count=100&patient:Patient.organization:Organization.name=Mollis');`
                                                                            explain_search
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=140.45..188.98 rows=100 width=459) (actual time=2.369..1518.992 rows=57 loops=1)
   ->  Nested Loop  (cost=140.45..32496.71 rows=66667 width=459) (actual time=2.369..1518.976 rows=57 loops=1)
         ->  Nested Loop  (cost=17.02..726.56 rows=5 width=37) (actual time=2.320..1517.130 rows=42 loops=1)
               Join Filter: (fhirbase_idx_fns.index_as_reference(patient.content, '{managingOrganization}'::text[]) && ARRAY[organization.logical_id])
               Rows Removed by Join Filter: 18782
               ->  Seq Scan on organization  (cost=0.00..157.89 rows=5 width=37) (actual time=0.200..33.105 rows=4 loops=1)
                     Filter: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Mollis%'::text)
                     Rows Removed by Filter: 487
               ->  Materialize  (cost=17.02..436.43 rows=100 width=1173) (actual time=0.474..108.069 rows=4706 loops=4)
                     ->  Bitmap Heap Scan on patient  (cost=17.02..435.93 rows=100 width=1173) (actual time=1.864..412.177 rows=4706 loops=1)
                           Recheck Cond: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Abe%'::text)
                           Heap Blocks: exact=2325
                           ->  Bitmap Index Scan on fb_patient_name_name_string_idx  (cost=0.00..17.00 rows=100 width=0) (actual time=1.292..1.292 rows=4706 loops=1)
                                 Index Cond: (fhirbase_idx_fns.index_as_string(content, '{name}'::text[]) ~~* '%Abe%'::text)
         ->  Bitmap Heap Scan on encounter  (cost=123.42..6220.70 rows=13333 width=459) (actual time=0.039..0.040 rows=1 loops=42)
               Recheck Cond: (fhirbase_idx_fns.index_as_reference(content, '{patient}'::text[]) && ARRAY[patient.logical_id])
               Heap Blocks: exact=57
               ->  Bitmap Index Scan on fb_encounter_patient_patient_reference_idx  (cost=0.00..120.09 rows=13333 width=0) (actual time=0.035..0.035 rows=1 loops=42)
                     Index Cond: (fhirbase_idx_fns.index_as_reference(content, '{patient}'::text[]) && ARRAY[patient.logical_id])
 Planning time: 0.780 ms
 Execution time: 1530.421 ms
(21 rows)

**Comment by niquola** [comment]
moved to https://github.com/fhirbase/fhirbase-plv8/issues/11
