### ISSUE TITLE
Searching Encounters for patients within a organization (or no middle join criteria)

### ISSUE THREAD

**Issue by chinnitv** [fhirbase/fhirbase#132]
The below search fails because patient table is not joined at all.
Apparently there is a TODO at this [line](https://github.com/fhirbase/fhirbase/blob/master/src/fhirbase_search.sql#L236)
--TODO: what if no middle join present ie we have a.b.c.attr = x and no a.b.attr condition

`fhirbase=# select fhir._search('Encounter','patient:Patient.organization:Organization.name=Lectus');`
> ERROR:  missing FROM-clause entry for table "patient"
> LINE 2: ...ganization ON fhirbase_idx_fns.index_as_reference(patient.co...
                                                                                                      ^
> QUERY:  SELECT encounter.version_id, encounter.logical_id, encounter.resource_type, encounter.updated, encounter.published, encounter.category, encounter.content FROM encounter
JOIN organization ON fhirbase_idx_fns.index_as_reference(patient.content, '{managingOrganization}') && ARRAY[organization.logical_id]::text[] AND
 (fhirbase_idx_fns.index_as_string(organization.content, '{name}') ilike '%Lectus%')
WHERE  true = true
LIMIT 100
OFFSET 0
CONTEXT:  PL/pgSQL function fhirbase_search.search(text,text) line 4 at RETURN QUERY
SQL function "_search" statement 1

**Comment by niquola** [comment]
Moved to https://github.com/fhirbase/fhirbase-plv8/issues/10
