### ISSUE TITLE
Question regarding the implementation

### ISSUE THREAD

**Issue by harikt** [fhirbase/fhirbase#134]
Hi, 

I was trying to explore the project and have a few questions.

Installed the fhirbase.

1. I am seeing the structure of the schema for table is a bit different than the one I am seeing in the website. Eg : Person https://hl7-fhir.github.io/patient.html#5.1.2 , there is no schema for person or a table created. But I do see the `resources` table which contain the json.

My thoughts were this was actually creating the table structure.

May be I misunderstood? Can anyone help me to understand where to start ?

Thank you.

**Comment by wanghaisheng** [comment]
i assume you have followed the instructions here https://github.com/fhirbase/fhirbase/blob/master/docs/installation.md
when you run the following 

fhirbase-# \d
                      List of relations
 Schema |             Name             |   Type   |  Owner   
--------+------------------------------+----------+----------
 public | conceptmap                   | table    | postgres
 public | conceptmap_history           | table    | postgres
 public | modules                      | table    | postgres
 public | operationdefinition          | table    | postgres
 public | operationdefinition_history  | table    | postgres
 public | resource                     | table    | postgres
 public | resource_history             | table    | postgres
 public | schema                       | table    | postgres
 public | searchparameter              | table    | postgres
 public | searchparameter_history      | table    | postgres
 public | structuredefinition          | table    | postgres
 public | structuredefinition_elements | table    | postgres
 public | structuredefinition_history  | table    | postgres
 public | test                         | table    | fhirbase
 public | test_id_seq                  | sequence | fhirbase
 public | valueset                     | table    | postgres
 public | valueset_history             | table    | postgres
(17 rows)
what all you got is these base table and parent table,if you want to get table for each resource you can run
fhirbase=# SELECT fhir.generate_tables();
 generate_tables 
-----------------
 86
(1 row)

**Comment by wanghaisheng** [comment]
i assume you have followed the instructions here https://github.com/fhirbase/fhirbase/blob/master/docs/installation.md
when you run the following 

fhirbase-# \d
                      List of relations
 Schema |             Name             |   Type   |  Owner   
--------+------------------------------+----------+----------
 public | conceptmap                   | table    | postgres
 public | conceptmap_history           | table    | postgres
 public | modules                      | table    | postgres
 public | operationdefinition          | table    | postgres
 public | operationdefinition_history  | table    | postgres
 public | resource                     | table    | postgres
 public | resource_history             | table    | postgres
 public | schema                       | table    | postgres
 public | searchparameter              | table    | postgres
 public | searchparameter_history      | table    | postgres
 public | structuredefinition          | table    | postgres
 public | structuredefinition_elements | table    | postgres
 public | structuredefinition_history  | table    | postgres
 public | test                         | table    | fhirbase
 public | test_id_seq                  | sequence | fhirbase
 public | valueset                     | table    | postgres
 public | valueset_history             | table    | postgres
(17 rows)
what all you got is these base table and parent table,if you want to get table for each resource you can run
fhirbase=# SELECT fhir.generate_tables();
 generate_tables 
-----------------
 86
(1 row)

**Comment by wanghaisheng** [comment]
i assume you have followed the instructions here https://github.com/fhirbase/fhirbase/blob/master/docs/installation.md
when you run the following 

fhirbase-# \d
                      List of relations
 Schema |             Name             |   Type   |  Owner   
--------+------------------------------+----------+----------
 public | conceptmap                   | table    | postgres
 public | conceptmap_history           | table    | postgres
 public | modules                      | table    | postgres
 public | operationdefinition          | table    | postgres
 public | operationdefinition_history  | table    | postgres
 public | resource                     | table    | postgres
 public | resource_history             | table    | postgres
 public | schema                       | table    | postgres
 public | searchparameter              | table    | postgres
 public | searchparameter_history      | table    | postgres
 public | structuredefinition          | table    | postgres
 public | structuredefinition_elements | table    | postgres
 public | structuredefinition_history  | table    | postgres
 public | test                         | table    | fhirbase
 public | test_id_seq                  | sequence | fhirbase
 public | valueset                     | table    | postgres
 public | valueset_history             | table    | postgres
(17 rows)
what all you got is these base table and parent table,if you want to get table for each resource you can run
fhirbase=# SELECT fhir.generate_tables();
 generate_tables 
-----------------
 86
(1 row)

**Comment by wanghaisheng** [comment]
i assume you have followed the instructions here https://github.com/fhirbase/fhirbase/blob/master/docs/installation.md
when you run the following 

fhirbase-# \d
                      List of relations
 Schema |             Name             |   Type   |  Owner   
--------+------------------------------+----------+----------
 public | conceptmap                   | table    | postgres
 public | conceptmap_history           | table    | postgres
 public | modules                      | table    | postgres
 public | operationdefinition          | table    | postgres
 public | operationdefinition_history  | table    | postgres
 public | resource                     | table    | postgres
 public | resource_history             | table    | postgres
 public | schema                       | table    | postgres
 public | searchparameter              | table    | postgres
 public | searchparameter_history      | table    | postgres
 public | structuredefinition          | table    | postgres
 public | structuredefinition_elements | table    | postgres
 public | structuredefinition_history  | table    | postgres
 public | test                         | table    | fhirbase
 public | test_id_seq                  | sequence | fhirbase
 public | valueset                     | table    | postgres
 public | valueset_history             | table    | postgres
(17 rows)
what all you got is these base table and parent table,if you want to get table for each resource you can run
fhirbase=# SELECT fhir.generate_tables();
 generate_tables 
-----------------
 86
(1 row)

**Comment by wanghaisheng** [comment]
you can find  more info through https://github.com/fhirbase/fhirbase/blob/master/docs/overview.md

**Comment by harikt** [comment]
Thank you @wanghaisheng for the fast response. 

You are absolutely correct that I have ran up to 17 rows. Now I need to run `SELECT fhir.generate_tables();` .

I will look into the overview page. 

Thank you once again.
