### ISSUE TITLE
Schema based multi-tenancy.

### ISSUE THREAD

**Issue by izi** [fhirbase/fhirbase#136]
We need to have ability to server multiple clients from a single database. Currently fhirbase puts all resource tables in a single schema public. The other schemas contain stored procedures.

Ideally it would be possible to create the schema per tenant. The stored procedures would respect search_path so that SET search_path TO 'schema1' would effectively mean that we are using data only from schema1.

The possible extension would be to configure that separate schemas are stored in different tablespaces.

**Comment by niquola** [comment]
Hi, I think it's possible. Good idea to not polute global namespase.  It also could be used for complex migrations to new fhirbase/ FHIR versions - so different versions of fhirbase could coexist in one database. We'll take it into account for fhirbase 2.0!

**Comment by niquola** [comment]
Will be addressed in plv8 veresion
