### ISSUE TITLE
Reasoning behind DB Model

### ISSUE THREAD

**Issue by niedfelj** [fhirbase/fhirbase#15]
Hi,

Wondering if you can create docs explaining in more detail why you decided to make every resource type a separate db table instead of maybe one resource table with a type column?

**Comment by niquola** [comment]
big tables perform bad, indexes are different etc

**Comment by niedfelj** [comment]
Thanks at @niquola. Would be nice to have it on the page in the docs describing the database table setup.

**Comment by niquola** [comment]
Good idea, I will update documentation. Thank you.

**Comment by niquola** [comment]
done
