### ISSUE TITLE
Missing postgres functions after init/load

### ISSUE THREAD

**Issue by rdammkoehler** [fhirbase/fhirbase#17]
I followed the tutorial to create a fhirbase database. When I try to use the web-app many of the demo features don't work because the function fhirbase is not defined. 

> ERROR: function fhirpath(jsonb, unknown) does not exist (SQLSTATE 42883)

As a result I cannot complete the demo.

**Comment by mlapshin** [comment]
Hello, fhirpath function is not available in the free Fhirbase version. Please contact Health Samurai (hello@health-samurai.io) for licensing Fhirpath module.
