### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by sebastianhelbig** [fhirbase/fhirbase#36]
We are thinking about using this for one of our projects. Is development still ongoing?
- Last commit two years ago
- Latest binary release without support for FHIR R4

**Comment by niquola** [comment]
Hi @sebastianhelbig we are focused on the development of our FHIR platform - aidbox, which inherited a lot from fhirbase.
Sadly fhirbase development is not active - because we do not use it. If you are interested to re-activate this project - we will help you.

**Comment by sebastianhelbig** [comment]
Ok. Thank you for the quick answer and explanation! 👍
