### ISSUE TITLE
Versions migration mechanism

### ISSUE THREAD

**Issue by niquola** [fhirbase/fhirbase#65]
Publish new releases with migrations scripts to update running fhirbases

**Comment by filip-owczarzak** [comment]
Do you plan to support migration scripts running in transaction? Similar question about support for rollback?

**Comment by niquola** [comment]
Run migrations in transaction is not a problem.
Rollback is planned.

The major question how to work with user data, when structure changes are deep and breaking.

We plan automate simple migrations and give instructions & helpers for fixing data if required - so fhirbase clients could do it manually with full control.

Also hope that after FHIR DSTU-2 version freeze, changes will not be so radical.
As i know, freeze is planned in summer.

**Comment by niquola** [comment]
Now it could be done from checkout project:

```
./runme migrate && ./runme reload src/fhir.sql
```

But it's not perfect yet :( 
see #87
