### ISSUE TITLE
When creating search index, remember this in meta info  - SearchParameter.indexed

### ISSUE THREAD

**Issue by niquola** [fhirbase/fhirbase#71]

**Comment by maksym** [comment]
Когда дважды вызываешь второй раз падает потому что пытается выполнить код на создание
мы не знаем какие у нас поля проиндексированны а какие нет.
можно даже спросить что проиндексированно в удобном виде.

**Comment by filip-owczarzak** [comment]
Hi @maksym!

Tried to Goolge-translate and received something a bit clumsy. Actually was not suprised too much. Those translations more often give a clue, not exact meaning. Anyway, it is probably something internal, so no big deal. Yet in case it drops out into wider view, having all the conversation in english might improve communication.

**Comment by niquola** [comment]
translated
