### ISSUE TITLE
Function index_date.index_as_date is extremly slow

### ISSUE THREAD

**Issue by mlapshin** [fhirbase/fhirbase#75]
It takes about 24 hours to build date index on 50M of resources. It's ~24 times slower than `index_as_string` function.

We need to figure out how to speedup `index_as_date` function. No doubt it will be slower than trivial `index_as_string`, but not so much as now.

**Comment by mlapshin** [comment]
The only solution:

http://www.youtube.com/watch?v=XHosLhPEN3k

**Comment by niquola** [comment]
Same question as in #77
