### ISSUE TITLE
Can we optimize index_identifier_as_token fn?

### ISSUE THREAD

**Issue by mlapshin** [fhirbase/fhirbase#77]
It takes about 5.5 hours to index 50M indentifiers. So it's about 5 times slower than `index_as_string` function. Can we somehow optimize it?

**Comment by niquola** [comment]
@mlapshin could you describe concrete and reproducible test case (which does not take 5h) - to start fighting this issue?

I.e. concrete resource, concrete index and reasonable amount of data.

**Comment by niquola** [comment]
Moved to https://github.com/fhirbase/fhirbase-plv8/issues/20
