### ISSUE TITLE
crud.history function is useless on database with huge amount of resources

### ISSUE THREAD

**Issue by mlapshin** [fhirbase/fhirbase#78]
`crud.history` function has no ability to limit amount of returning data.

So on database with large amount of resources it will literally try to select all existing resources + all of theirs versions.

We should add `limit` and `offset` parameters to make this function useful.

**Comment by niquola** [comment]
ya and set some default limit

**Comment by Bazai** [comment]
At the moment there are 3 overloading versions for `crud.search`:

```sql
func! history(_cfg_ jsonb, _resource_type_ text, _id_ text)
func! history(_cfg_ jsonb, _resource_type_ text)
func! history(_cfg_ jsonb)
```

And at first glance it seems not so hard to change function signatures and add two new params such as `_limit_` and `_offset_`:

```sql
func! history(_cfg_ jsonb, _limit_, _offset_, _resource_type_ text, _id_ text)
func! history(_cfg_ jsonb,  _limit_, _offset_,_resource_type_ text)
func! history(_cfg_ jsonb, _limit_, _offset_)
```

However, it's all about Paging and FHIR standard describes it in documentation as (surprise!) [Paging](http://hl7-fhir.github.io/http.html#paging). And as I understand, `search` and `history` should implement similar interface, but in `search` it's already made with query string:

```sql
select fhir.search('Patient', 'given=mark&count=10&page=3')
```

So, to be more consistent, `crud.history` should extend same approach and signature should change to something like (`_query_string_ text` added as last param):

```sql
func! history(_cfg_ jsonb, _resource_type_ text, _id_ text, _query_string_ text)
```

To get `fhir.history` something like:

```sql
SELECT fhir.history('Patient', 'logical-id', 'count=100');
SELECT fhir.history('Patient', 'logical-id', 'count=100&page=22');
SELECT fhir.history('Patient', 'count=100');
SELECT fhir.history('Patient', 'count=100&page=22');
```

What do you think?
