### ISSUE TITLE
Error codes 

### ISSUE THREAD

**Issue by czajek** [fhirbase/fhirbase#79]
Right now it's not possible to identify certain situations because exceptions thrown by FhirBase always include same SQL error code (P0001 RISE EXCEPTION). Ideally there should be 1 to 1 mapping between REST api errors and  FHIRBase errors. This could be achieved by providing custom SQL code when throwing exception or returning OperationalOutcome.

**Comment by niquola** [comment]
@czajek in which concrete operations are you interested now? CRUD?

**Comment by niquola** [comment]
I like to return OperationOutcome for clients code convenience - it's not trivial to handle postgresql exceptions in app layer.

**Comment by czajek** [comment]
We use stored procedures from fhir schema. Right now we have implemented all CRUD methods and that would be our priority for now. Do you have any idea how to map Operation Outcome to HTTP codes?

**Comment by niquola** [comment]
We could extend OperationOutcome with status - symbolic or just http code

**Comment by czajek** [comment]
That would be great. Both (symbolic or http code) are good for us.

**Comment by czajek** [comment]
@niquola do you have plans when this will be implemented?

**Comment by niquola** [comment]
@czajek if this issue is critical for you, i can implement OperationOutcome on CRUD today.

For chat discussion use [fhirbase gitter chat](https://gitter.im/fhirbase/fhirbase?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by czajek** [comment]
@niquola if this can be done today, that would be great

**Comment by niquola** [comment]
@czajek it would be something like:

SELECT fhir.create('{resourceType: "Unexisting"}') =>

```json
{  
   "issue":[  
      {  
         "code":{  
            "coding":[  
               {  
                  "code":"invalid",
                  "system":"http://hl7.org/fhir/issue-type",
                  "display":"Invalid Content"
               },
               {  
                  "code":"404",
                  "system":"http://hl7.org/fhir/http-code",
                  "display":"Not Found"
               }
            ]
         },
         "details":"resource type unexisitng not supported, or not a FHIR end point",
         "severity":"error"
      }
   ],
   "resourceType":"OperationOutcome"
}
```
