### ISSUE TITLE
Postgresql schema layout - multi tenancy question

### ISSUE THREAD

**Issue by izi** [fhirbase/fhirbase#80]
Currently FHIRbase creates a lot of schemas with functions and leaves all the tables with data in the public schema. This allows multi tenancy only at the database level. We are evaluating currently approach with database per tenant but it comes with a set of challenges.

I wonder if it is possible and how much effort would be involved in parametrising the creation of tables/functions/schemas with some tenant prefix. For example FHIRbase installation could create 3 schemas per tenant:

    tenant_name_data
    tenant_name_functions
    tenant_name_internal_functions
default name per single installation could be:

    fhirbase_data
    fhirbase_functions

The other approach would be all in one schema:

    tenant_name

If the database per tenant evaluation will go wrong we may need to look at this approach. Is it something that you would accept in your code base? What kind of approach do you want to introduce for fhirbase namespaces?

**Comment by niquola** [comment]
Prefix all fhirbase schemas sounds reasonable and already in our plans.

We experimented with different schemas to install resource tables and
parametrize procedures with schema - this make API little bit complicated
and require to decide about share/not share meta data (i.e. resources
definitions, search params etc).

If we will implement multi-schema fhirbase, I think, this feature should be
optional - without impact on simplicity of common usage of fhirbase.

All in one schema looks like a wrong way.

How many tenants do you expect?
And what is expected size  of tenants or distribution by size (a lot of
small and several large for example)?

I see, separate database for tenant gives isolation and scalability, but
also brings a lot of challenges.

Obvious one is deploy and need to support plenty of databases.

What are essential cons for you on that way?

73's nicola
