### ISSUE TITLE
ERROR: 42P01: relation "claim" does not exist

### ISSUE THREAD

**Issue by lisney** [fhirbase/fhirbase#88]
I wrote a generic tests for CRUD-operations using "examples-json.zip" downloaded from http://fhir-ru.github.io/downloads.html. And send resources from files like "[resource] -example.json". I received the following error for "clinicalimpression-example.json", "claim-...", "clinicalimpression-.." and "processrequest-...":
* ERROR: 42P01: relation "clinicalimpression" does not exist
* ERROR: 42P01: relation "claim" does not exist
* ERROR: 42P01: relation "clinicalimpression" does not exist, 
* ERROR: 42P01: relation "processrequest" does not exist

The database was created using "fhir.generate_tables ()".

claim-example.json:
```json
{
  "resourceType": "Claim",
  "text": {
    "status": "generated",
    "div": "<div>A human-readable rendering of the Oral Health Claim</div>"
  },
  "type": "oral",
  "identifier": [
    {
      "system": "http://happyvalley.com/claim",
      "value": "12345"
    }
  ],
  "created": "2014-08-16",
  "target": {
    "reference": "Organization/2"
  },
  "organization": {
    "reference": "Organization/1"
  },
  "use": "complete",
  "priority": {
    "code": "normal"
  },
  "payee": {
    "type": {
      "code": "provider"
    }
  },
  "diagnosis": [
    {
      "sequence": 1,
      "diagnosis": {
        "code": "123456"
      }
    }
  ],
  "patient": {
    "reference": "Patient/1"
  },
  "coverage": [
    {
      "sequence": 1,
      "focal": true,
      "coverage": {
        "reference": "Coverage/9876B1"
      },
      "relationship": {
        "code": "self"
      }
    }
  ],
  "item": [
    {
      "sequence": 1,
      "type": {
        "code": "service"
      },
      "provider": {
        "reference": "Practitioner/1"
      },
      "service": {
        "code": "1200"
      },
      "serviceDate": "2014-08-16",
      "unitPrice": {
        "value": 135.57,
        "system": "urn:std:iso:4217",
        "code": "USD"
      },
      "net": {
        "value": 135.57,
        "system": "urn:std:iso:4217",
        "code": "USD"
      }
    }
  ]
}
```

**Comment by niquola** [comment]
Which version of fhirbase?
Hi, you can inspect available resources by `select * from structuredefinition where kind='resource'`.

I've updated metadata 2 days ago, but you have to reinstall fhirbase - we are working on smooth migrations for fhirbase users.

**Comment by lisney** [comment]
The test result didn't change after the update FHIRbase from the master branch. 
*clinicalimpression*, *claim* and *processrequest* don't appear in the query result (resources select * from structuredefinition where kind='resource')

**Comment by niquola** [comment]
You have to recreate database, then call `fhir.generate_tables()` - or just
call ./runme integrate - but you will loose all data
