### ISSUE TITLE
DiagnosticOrder specimen searchparameter

### ISSUE THREAD

**Issue by lisney** [fhirbase/fhirbase#89]
Query "select fhir.search('DiagnosticOrder', 'specimen=some_existing_code') " returns all resources.
Table "searchparameters" for "DiagnosticOrder" doesn't contain the path "specimen".

**Comment by niquola** [comment]
The problem is that some search params from fhir distribution does not have xpath - https://gist.github.com/niquola/9624540b41ef57d13dfa

Gonna fix some of them by hands :(

**Comment by niquola** [comment]
Addressed by - https://github.com/fhirbase/fhirbase-plv8/issues/19
