### ISSUE TITLE
Search returns everything instead of empty result with wrong query

### ISSUE THREAD

**Issue by szymonp-kainos** [fhirbase/fhirbase#90]
When search is called with wrong query (unrecognised key) fhirbase returns everything from requested resource type instead of empty result.

```sql
SELECT fhir.search_sql('Patient','id=42fa4d08-06a9-4da1-95ec-f829674bf6a2');
```
returns
```sql
SELECT patient.version_id, patient.logical_id, patient.resource_type, patient.updated, patient.published, patient.category, patient.content FROM patient
WHERE  true = true 
LIMIT 100
OFFSET 0
```

```sql
SELECT fhir.search_sql('Patient','_idd=42fa4d08-06a9-4da1-95ec-f829674bf6a2');
```
returns
```sql
SELECT patient.version_id, patient.logical_id, patient.resource_type, patient.updated, patient.published, patient.category, patient.content FROM patient
WHERE  true = true 
LIMIT 100
OFFSET 0
```

Same for keys not even close to existing ones
```sql
SELECT fhir.search_sql('Patient','something=42fa4d08-06a9-4da1-95ec-f829674bf6a2');
```
returns
```sql
SELECT patient.version_id, patient.logical_id, patient.resource_type, patient.updated, patient.published, patient.category, patient.content FROM patient
WHERE  true = true 
LIMIT 100
OFFSET 0
```

**Comment by niquola** [comment]
This behavior is expected by FHIR specification, ie ignore unknown parameters.
We've discussed this topic with Grahame twice and he is sure about this way.
I think we could create strict version of search - which will fail if non-existing params are passed.

You could always check what params are available for resource by:

```sql
select name, path from searchparameter where base = 'Patient'
```

**Comment by szymonp-kainos** [comment]
I can understand ignoring unknown but wouldn't it be better to return empty result when no params are specified or all are ignore ?
I think strict version of search would be awesome.

**Comment by niquola** [comment]
Could you reopen this discussion in a fhir skype chat ;) I'll join

**Comment by szymonp-kainos** [comment]
Done ; )

**Comment by niquola** [comment]
In plv8 version now it fails by default
