### ISSUE TITLE
Search by date using "greater or lower than" comparator includes boundary values

### ISSUE THREAD

**Issue by grzegorz-borczuch** [fhirbase/fhirbase#91]
When doing the search query using strict *=<* or *=>* comparators for dates FhirBase returns all dates that are before or after specified date (respectively) **plus** date that equals to specified date.
So currently *=<* or *=>* comparators for dates works like *=<=* or *=>=* comparators.

According to specification:
*[parameter]=>[date]" searches for all resources where the specified date is after [date]*
and
*For "[parameter]=>[date]", the requirement is that the interval of the time after [date] intersects (i.e. overlaps) with the interval of time in the relevant resource element.*

**Comment by niquola** [comment]
Will be done by https://github.com/fhirbase/fhirbase-plv8/issues/18
