### ISSUE TITLE
Search by date using "not equals" comparator returns empty results

### ISSUE THREAD

**Issue by grzegorz-borczuch** [fhirbase/fhirbase#93]
Using =!= comparator in FhirBase always returns empty results.
Looks like this comparator is not recognised, because in SQL that get's generated it's comparing dates to NULL. See SQL code generated below:
```
SELECT patient.version_id, patient.logical_id, patient.resource_type, patient.updated, patient.published, patient.category, patient.content
FROM patient 
WHERE (fhirbase_date_idx.index_as_date(content, '{birthDate}'::text[], 'date'::text) && NULL)
LIMIT 100
OFFSET 0
```
According to specification:
*For [parameter]=!=[date], the requirement is that the search interval does not fully contain the time of the target. i.e. [parameter]=!=2013-01-14 includes 2013-01-15T00:00 but not 2013-01-14T00:00 or 2013-01-14T10:00*

**Comment by niquola** [comment]
Hi,  thx for issue. I think this modifier was added recently. Gonna review
specification and fix it next week

**Comment by grzegorz-borczuch** [comment]
Yes, you’re right – there is no such operator in DSTU-1 version of specification.

Regards,
Grzegorz Borczuch

From: niquola
Reply-To: fhirbase/fhirbase
Date: Thursday 9 April 2015 11:02
To: fhirbase/fhirbase
Cc: Grzegorz Borczuch
Subject: Re: [fhirbase] Search by date using "not equals" comparator returns empty results (#93)

Hi, thx for issue. I think this modifier was added recently. Gonna review
specification and fix it next week
On Apr 9, 2015 10:42 AM, "grzegorz-borczuch" <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Using =!= comparator in FhirBase always returns empty results.
> Looks like this comparator is not recognised, because in SQL that get's
> generated it's comparing dates to NULL. See SQL code generated below:
>
> SELECT patient.version_id, patient.logical_id, patient.resource_type, patient.updated, patient.published, patient.category, patient.content
> FROM patient
> WHERE (fhirbase_date_idx.index_as_date(content, '{birthDate}'::text[], 'date'::text) && NULL)
> LIMIT 100
> OFFSET 0
>
> According to specification:
> *For [parameter]=!=[date], the requirement is that the search interval
> does not fully contain the time of the target. i.e.
> [parameter]=!=2013-01-14 includes 2013-01-15T00:00 but not 2013-01-14T00:00
> or 2013-01-14T10:00*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fhirbase/fhirbase/issues/93>.
>

—
Reply to this email directly or view it on GitHub<https://github.com/fhirbase/fhirbase/issues/93#issuecomment-91160922>.

Follow the Kainos buzz on: Twitter<https://twitter.com/kainossoftware> Facebook<https://www.facebook.com/KainosSoftware> Linkedin<http://www.linkedin.com/company/kainos> Youtube<http://www.youtube.com/user/KainosSoftware> Sunday Times Top 100<http://www.kainos.com/kainos-repeats-success-sunday-times-best-companies-work-rankings/>

This e-mail is intended solely for the addressee and is strictly confidential; if you are not the addressee please destroy the message and all copies. Any opinion or information contained in this email or its attachments that does not relate to the business of Kainos is personal to the sender and is not given by or endorsed by Kainos. This email has been scanned for all known viruses by EOP but is not guaranteed to be virus free; further terms and conditions may be found on our website - www.kainos.com "Kainos" is the trading name of the Kainos group of companies comprising the parent company, Kainos Software Limited, registered in Northern Ireland under company number: NI019370, having its registered offices at: Kainos House, 4-6 Upper Crescent, Belfast, BT7 1NT, Northern Ireland, and its wholly owned subsidiaries. The subsidiary details can be found here<http://www.kainos.com/discover-kainos/corporate-information/>.

**Comment by grzegorz-borczuch** [comment]
Have tested this one and it looks like it's still doesn't work correctly.
Now, the SQL that's generated looks like this:
```
SELECT patient.version_id, patient.logical_id, patient.resource_type, patient.updated, patient.published, patient.category, patient.content FROM patient
 
WHERE (not  (fhirbase_date_idx.index_as_date(content, '{birthDate}'::text[], 'date'::text) && NULL))
LIMIT 100
OFFSET 0
```
