### ISSUE TITLE
Search by datetime ignores TZ provided in query and always uses local server TZ

### ISSUE THREAD

**Issue by grzegorz-borczuch** [fhirbase/fhirbase#98]
For an Encounter in FhirBase with period set without using TZ suffix when providing TZ suffix in query it gets ignored.

According to specification:
*Where possible, the system should correct for timezones when performing queries. Dates do not have time zones, and time zones should not be considered. Where both search parameters and resource element date times do not have time zones, the servers local time zone should be assumed.*

**Comment by niquola** [comment]
Moved to https://github.com/fhirbase/fhirbase-plv8/issues/26
